FROM nginx:1.29-alpine-slim  
 # 너무 옛날 1.14 말고, 좀 최신/안전한 버전으로


# 기본 conf 덮어쓰기
COPY default.conf /etc/nginx/conf.d/default.conf

# 필요한 정적 파일 있으면 같이 복사 (없으면 이 줄은 삭제)
# COPY html/ /usr/share/nginx/html

EXPOSE 80

# nginx 이미 기본 CMD가 있어서 사실 이 줄도 없어도 됨
 CMD ["nginx", "-g", "daemon off;"]
